name: tests

on:
  pull_request:
    paths:
      - "tickets/**"

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd tickets && npm install && npm run test:ci
